# MCI-Drupal docker-compose.yml v2.1 see details in docs/docker-compose.yml
# 2017 (C) @MacMladen

version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    restart: unless-stopped
    # Uncomment these two lines and "tunnel" them to have PhpStorm or other client access
#    ports:
#      - "8006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      # Place init .sql file(s) here, those will be automatically imported on container creation.
#      - ./databases/init:/docker-entrypoint-initdb.d
      - ./runtime/mariadb:/var/lib/mysql
      - ./databases:/var/lib/mysql/databases


  php:
    image: wodby/drupal-php:7.1-2.4.9
#    image: wodby/drupal-php:5.6-2.4.9
    restart: unless-stopped
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      # New variables
      PHP_XDEBUG: 1                      # Enable Xdebug extension
      PHP_XDEBUG_DEFAULT_ENABLE: 1       # Comment out to disable (default).
      #PHP_XDEBUG_REMOTE_AUTOSTART: 1     # Comment out to disable (default).
      # Mac OS X only
      #PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      #PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
    volumes:
      # - codebase:/var/www/html
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx
    restart: unless-stopped
#    ports:
#      - "8100:80"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/webroot
    volumes:
      # - codebase:/var/www/html
      - ./:/var/www/html
    networks:
      - default
      - traefik_proxy
    labels:
      - 'traefik.backend=news_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:news.dev.loc'
      - "traefik.docker.network=traefik_proxy"

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
#    ports:
#     - "8001:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
#    volumes:
#      - ./runtime/metro:/www/themes/metro
      # Add custom pma configuration e.g. to prevent timeout https://docs.phpmyadmin.net/en/latest/config.html#config
#      - ./runtime/pma-config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - default
      - traefik_proxy
    labels:
      - 'traefik.backend=news_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:news.pma.loc'
      - "traefik.docker.network=traefik_proxy"

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
#    ports:
#      - "8002:8025"
    networks:
      - default
      - traefik_proxy
    labels:
      - 'traefik.backend=news_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:news.hog.loc'
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external: true